### PR TITLE
Remove pytest from run dependencies

### PR DESCRIPTION
**Pull request by gsakkis**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martindurant** [comment]
Fixes #26

**Comment by martindurant** [comment]
Can you please inc the build number [here](https://github.com/conda-forge/fastparquet-feedstock/pull/26/files#diff-e178b687b10a71a3348107ae3154e44cR14) ?

**Comment by gsakkis** [comment]
@martindurant can this be merged? The appveryor failure is unrelated (`Connection to repo.anaconda.com timed out`)

**Comment by martindurant** [comment]
Sorry to keep you waiting

**Comment by gsakkis** [comment]
Thanks, no worries. However I'm still getting the previous versions when trying to install and `conda search` doesn't show it:
```
$ conda search --override-channels -c conda-forge 'fastparquet>=0.3'
Loading channels: done
# Name                  Version           Build  Channel             
fastparquet               0.3.1  py27h516909a_0  conda-forge         
fastparquet               0.3.1  py36h516909a_0  conda-forge         
fastparquet               0.3.1  py37h516909a_0  conda-forge         
```
Does it work for you?

**Comment by martindurant** [comment]
Build 01 files do show up here: https://anaconda.org/conda-forge/fastparquet/files

I also see it on an install:
```
(py37) mdurant@blackleaf:~$ conda create -n testme fastparquet=0.3.1
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/mdurant/anaconda/envs/testme

  added / updated specs:
    - fastparquet=0.3.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.6.16          |           py37_0         154 KB
    fastparquet-0.3.1          |   py37h01d97ff_1         237 KB  conda-forge   ######
    intel-openmp-2019.4        |              233         1.1 MB
    llvmlite-0.29.0            |   py37h98b8051_0        13.7 MB
    mkl-2019.4                 |              233       155.2 MB
    numba-0.44.1               |   py37h6440ff4_0         2.8 MB
    numpy-1.16.4               |   py37hacdab7b_0          49 KB
    numpy-base-1.16.4          |   py37h6575580_0         4.2 MB
    pandas-0.24.2              |   py37h0a44026_0         9.9 MB
    pytz-2019.1                |             py_0         236 KB
    thrift-0.11.0              |   py37h0a44026_0         100 KB
    ------------------------------------------------------------
```

**Comment by gsakkis** [comment]
Now it works for me too; caching issue I guess.

**Pull request merged**
