### PR TITLE
Fix packaged version.

### PR DESCRIPTION
**Pull request by TomAugspurger**
Fixup for https://github.com/conda-forge/fastparquet-feedstock/pull/20

cc @martindurant.

We'll need to remember to reset the build number to 0 on the next build.

### CODE REVIEW

**Comment by martindurant** [comment]
I wonder how it go to be like this...

**Comment by TomAugspurger** [comment]
Seems like the fn vs. fn_suffix split goes back a ways. And presumably the
retro-bot doesn't handle it well.

**Comment by TomAugspurger** [comment]
The circleci failures may be due to a dockerhub outage.

**Comment by martindurant** [comment]
Agreed. Better wait a little while.

**Comment by martindurant** [comment]
By the way, RTD build also failed on the last merge https://readthedocs.org/projects/fastparquet/builds/8294621/

**Comment by TomAugspurger** [comment]
Going to merge.

I don't have a guess for the RTD build... A bit of googling suggests that can happen when you try to get the git hash for an empty repo, but that doesn't make sense here.

**Pull request merged**
