### PR TITLE
v0.3.1 and pip

### PR DESCRIPTION
**Pull request by martindurant**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martindurant** [comment]
@conda-forge-admin, please rerender

**Comment by martindurant** [comment]
@conda-forge-admin, please rerender

**Comment by martindurant** [comment]
@msarahan , do you know what "RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml" means, what package it's trying to download?

**Comment by martindurant** [comment]
@conda-forge-admin, please rerender

**Comment by msarahan** [comment]
I think you've figured it out, but it is output in the error message:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=30718&view=logs&jobId=b5d7fd4c-4b5c-5f48-3f83-bd2b416ab539&taskId=1b9e5a0a-5a1b-5a69-5e00-436713ffcdaf&lineStart=489&lineEnd=489&colStart=5&colEnd=154

The URL there points to numpy missing.

**Comment by martindurant** [comment]
But numpy is in host (for compiling) build and run too - where is it missing?

**Comment by msarahan** [comment]
Things can also be "missing" if they are present, but don't match a constraint that's present in your requirements.  Look in setup.py or requirements.txt.  Does numpy requirement there match the one that conda is providing?

**Comment by martindurant** [comment]
requirements.txt is pretty simple:
```
pandas>=0.19
numba>=0.28
numpy>=1.11
thrift>=0.11.0
six
```
and build says installing as below, only higher or matching versions of these
```
...
    cython:          0.29.7-py27he1b5a44_0    conda-forge
    numba:           0.41.0-py27h637b7d7_1000 conda-forge
    numpy:           1.9.3-py27he5ce36f_1209  conda-forge
    pandas:          0.23.4-py27h637b7d7_1000 conda-forge
    six:             1.12.0-py27_1000         conda-forge
    thrift:          0.11.0-py27hf484d3e_1001 conda-forge
...
```

recipe is now ("latest" should be fine for everything)
```
  build:
    - python
    - pip
    - setuptools
    - cython
    - numpy
    - pytest-runner
    - numba
    - thrift
    - pandas
    - {{ pin_compatible('numpy') }}
  host:
    - {{ compiler('c') }}
    - python
    - pandas
    - pip
    - setuptools
    - numpy
    - pytest-runner
    - numba
    - thrift
```

**Comment by msarahan** [comment]
```
numpy>=1.11
```

and

```
numpy:           1.9.3-py27he5ce36f_1209  conda-forge
```

**Comment by martindurant** [comment]
OK, that did it, sorry for the hassle @msarahan and thank you

**Pull request merged**
